require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/company_targets", type: :request do
  # CompanyTarget. As you add validations to CompanyTarget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CompanyTarget.create! valid_attributes
      get company_targets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      company_target = CompanyTarget.create! valid_attributes
      get company_target_url(company_target)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_company_target_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      company_target = CompanyTarget.create! valid_attributes
      get edit_company_target_url(company_target)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CompanyTarget" do
        expect {
          post company_targets_url, params: { company_target: valid_attributes }
        }.to change { CompanyTarget.count }.by(1)
      end

      it "redirects to the created company_target" do
        post company_targets_url, params: { company_target: valid_attributes }
        expect(response).to redirect_to(company_target_url(CompanyTarget.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CompanyTarget" do
        expect {
          post company_targets_url, params: { company_target: invalid_attributes }
        }.to change { CompanyTarget.count }.by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post company_targets_url, params: { company_target: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested company_target" do
        company_target = CompanyTarget.create! valid_attributes
        patch company_target_url(company_target), params: { company_target: new_attributes }
        company_target.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the company_target" do
        company_target = CompanyTarget.create! valid_attributes
        patch company_target_url(company_target), params: { company_target: new_attributes }
        company_target.reload
        expect(response).to redirect_to(company_target_url(company_target))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        company_target = CompanyTarget.create! valid_attributes
        patch company_target_url(company_target), params: { company_target: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested company_target" do
      company_target = CompanyTarget.create! valid_attributes
      expect {
        delete company_target_url(company_target)
      }.to change { CompanyTarget.count }.by(-1)
    end

    it "redirects to the company_targets list" do
      company_target = CompanyTarget.create! valid_attributes
      delete company_target_url(company_target)
      expect(response).to redirect_to(company_targets_url)
    end
  end
end
