require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/department_targets", type: :request do
  # DepartmentTarget. As you add validations to DepartmentTarget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DepartmentTarget.create! valid_attributes
      get department_targets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      department_target = DepartmentTarget.create! valid_attributes
      get department_target_url(department_target)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_department_target_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      department_target = DepartmentTarget.create! valid_attributes
      get edit_department_target_url(department_target)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DepartmentTarget" do
        expect {
          post department_targets_url, params: { department_target: valid_attributes }
        }.to change { DepartmentTarget.count }.by(1)
      end

      it "redirects to the created department_target" do
        post department_targets_url, params: { department_target: valid_attributes }
        expect(response).to redirect_to(department_target_url(DepartmentTarget.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DepartmentTarget" do
        expect {
          post department_targets_url, params: { department_target: invalid_attributes }
        }.to change { DepartmentTarget.count }.by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post department_targets_url, params: { department_target: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested department_target" do
        department_target = DepartmentTarget.create! valid_attributes
        patch department_target_url(department_target), params: { department_target: new_attributes }
        department_target.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the department_target" do
        department_target = DepartmentTarget.create! valid_attributes
        patch department_target_url(department_target), params: { department_target: new_attributes }
        department_target.reload
        expect(response).to redirect_to(department_target_url(department_target))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        department_target = DepartmentTarget.create! valid_attributes
        patch department_target_url(department_target), params: { department_target: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested department_target" do
      department_target = DepartmentTarget.create! valid_attributes
      expect {
        delete department_target_url(department_target)
      }.to change { DepartmentTarget.count }.by(-1)
    end

    it "redirects to the department_targets list" do
      department_target = DepartmentTarget.create! valid_attributes
      delete department_target_url(department_target)
      expect(response).to redirect_to(department_targets_url)
    end
  end
end
